# Generated by Django 4.2.1 on 2023-06-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formularioos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('descripcion', models.CharField(max_length=500, verbose_name='descripcion')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Formularioo',
                'verbose_name_plural': 'Formularioos',
            },
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=90, verbose_name='Zona')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
                ('pueblo', models.CharField(max_length=100, verbose_name='Nombre Pueblo')),
                ('accesibilidad', models.CharField(max_length=300, verbose_name='Accesibilidad')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Restaurantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Actualización')),
                ('ubicacion', models.ManyToManyField(to='restaurantes.ubicaciones', verbose_name='Ubicaciones')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
            },
        ),
    ]
